name: Release Node.js versions

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ["22.3.0"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Node.js
      run: |
        curl -LO https://nodejs.org/dist/v${{ matrix.node_version }}/node-v${{ matrix.node_version }}-darwin-x64.tar.gz

    - name: Upload Binaries to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: node-v${{ matrix.node_version }}-darwin-x64.tar.gz
        asset_name: node-v${{ matrix.node_version }}-darwin-x64.tar.gz
        tag: node-${{ matrix.node_version }}-macos11
        overwrite: false
