name: Release Python versions

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.12.4", "3.8.10"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Python
      run: |
        curl -LO https://www.python.org/ftp/python/${{ matrix.python_version }}/python-${{ matrix.python_version }}-macos11.pkg

    - name: Upload Binaries to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: python-${{ matrix.python_version }}-macos11.pkg
        asset_name: python-${{ matrix.python_version }}-macos11.pkg
        tag: python-${{ matrix.python_version }}-macos11
        overwrite: false
